
name: Java CI with Ant

on:
  push:
    branches:  [ master ]
  pull_request:
    branches:  [ master ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        runs-on: [windows-latest]

    name: Test on Java ${{ matrix.Java }} on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'adopt'

    - name: Set up env
      run: |
        mkdir temp
        # Get one OSB project required for running tests
        mkdir osb/cerebellum
        mkdir osb/cerebellum/cerebellar_granule_cell
        git clone https://github.com/OpenSourceBrain/GranuleCell.git osb/cerebellum/cerebellar_granule_cell/GranuleCell
        echo Set up additional folders...
        ls

    - name: Build project and run tests (Win)
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        ./updatenC.bat # Pull other repos, e.g. NeuroML v1 examples from SourceForge
        echo "Everything pulled..."
        # make
        ./nC.bat -make
        # Rebuild & perform a number of tests with ant
        ./nC.bat -v
      shell: bash

    - name: Package artifacts to ZIP
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        $sourceDirs = "./"  # 根据实际路径调整
        $artifactFiles = Get-ChildItem -Path $sourceDirs -Recurse -ErrorAction SilentlyContinue
        if ($artifactFiles) {
          Compress-Archive -Path $sourceDirs -DestinationPath build-artifacts.zip
        } else {
          Write-Host "##[warning] No artifacts found to package."
        }
      shell: powershell
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build-artifacts.zip
